services:
  postgres:
    image: postgres:15-alpine
    container_name: blaze-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blaze_user
      POSTGRES_PASSWORD: blaze_password
      POSTGRES_DB: blaze_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: blaze-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: blaze-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: blaze_admin
      MINIO_ROOT_PASSWORD: blaze_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
